import { type Options } from "orval";

interface OrvalConfig {
  orval: Options;
}

const orvalConfig: OrvalConfig = {
  orval: {
    input: {
      target: "public/openapi.json",
    },
    output: {
      baseUrl: "/api",
      target: "orval/generated/",
      mode: "tags-split",
      client: "react-query",
      prettier: true,
      override: {
        header: (info: any): string =>
          `// @ts-nocheck\n\n/**\n * ${[
            `Auto Generated by orval`,
            `Do not edit manually.`,
            ...(info.title ? [`${info.title}`] : []),
            ...(info.description ? [`${info.description}`] : []),
          ].join("\n * ")}\n */\n\n`,
        mutator: {
          path: "./lib/axiosInstance.ts",
          name: "customAxios",
        },
        useNativeEnums: true,
      },
    },
  },
};

export default orvalConfig;
